name: Linter Workflow

on:
    push:
        branches:
            - main
    workflow_dispatch:
env:
    Test: test
    GREET_ROOT: 'Servus'
jobs:
    build-test:
        runs-on: ubuntu-latest
        needs: console
        env:
            Test: test
        strategy:
            matrix:
                version: [11, 17, 21]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: ${{ matrix.version }}
            
            - name: Build and Test with Maven
              run: mvn -B clean verify

            - name: Archive test results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: junit-results
                path: target/surefire-reports/
    
    linter:
        runs-on: ubuntu-latest
        needs: console
        env: 
            Test: test
        strategy:
            matrix:
                version: [11, 17, 21]
        steps: 
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: ${{ matrix.version }}
                
            - name: Linter test
              run: mvn checkstyle:checkstyle

            - name: Archive checkstyle results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: checkstyle-results
                path: target/

    console:
        runs-on: ubuntu-latest
        env: 
            Test: test
            GREET_JOB: 'Alexander'
        steps:
            - name: Greetings
              env:
                GREET_STEP: 'Login'
              run: echo $GREET_ROOT $GREET_JOB, das Passwort für $GREET_STEP ist ${{ secrets.PASSWORD }} 
